---
title: "University of Washington: POLS/CS&SS 501"
---

<p class="lead">
University of Washington, Winter 2017
</p>


## Instructors

<table class = "table table-striped">
<tr>
<td>
<strong>Primary</strong>
</td>
<td><a href="http://jrnold.me">Jeffrey Arnold</a></td>
<td><a href="mailto:jrnold@uw.edu">jrnold@uw.edu</a></td>
</tr>
<tr>
<td>
<strong></strong>
</td>
<td>
<a href="http://students.washington.edu/nww3/">Nora Webb Williams</a>
</td>
<td>
<a href="mailto:nww3@uw.edu">nww3@uw.edu</a>
</td>
</tr>
</table>

## Class Meetings

<table class = "table table-striped table-hover">
<tr>
<td>Class </td>
<td>Tu </td>
<td> 4:30&ndash;7:20 pm </td>
<td><a href="https://www.washington.edu/maps/?sav">SAV 162</a></td>
</tr>
<tr>
<td>Lab </td>
<td>Fri </td>
<td>1:30&ndash;3:20 pm </td>
<td><a href="https://www.washington.edu/maps/?sav">SAV 121</a> <br/>
(<a href="http://julius.csscr.washington.edu/about/labs.html">The CSSCR Small Lab</a>)</td>
</tr>
</table>


## Office Hours

<table class = "table table-striped">
<tr>

<!-- </tr> -->
<!--   <tr> -->
<!--     <td>Andreu</td> -->
<!--     <td>Monday</td> -->
<!--     <td>12:30&ndash;2:30 pm</td> -->
<!-- 	<td><a href="https://www.washington.edu/maps/?smi"> SMI 221 </td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>Jeff</td> -->
<!--     <td>Tuesday</td> -->
<!--     <td>2:30&ndash;3:30 pm</td> -->
<!-- 	<td><a href="https://www.washington.edu/maps/?smi">SMI 221B</a></td> -->
<!--   </tr> -->
<!--   <tr> -->
<!--     <td>Jeff</td> -->
<!--     <td>Wednesday</td> -->
<!--     <td>9:00&ndash;10:00 am</td> -->
<!-- 	<td><a href="https://www.washington.edu/maps/?smi">SMI 221B</a></td> -->
<!--   </tr> -->
<!-- </table> -->

<!-- Instructions for Jeff's office hours: -->

<!-- - Sign up for a slot on Canvas using the Scheduler tab in the Calendar. -->
<!-- - Email me 24 hours prior to your appointment with what you would like to discuss. -->

<!-- These instructions will ensure that our time is efficiently spent and I can be of the most help to you. -->

## Communication

For questions about the course that would be of general interest to all students in the course, email the course mailing list, [multi_pols501a_wi16@uw.edu](mailto:multi_pols501a_wi16@uw.edu), rather than the individual instructors.
Please reserve emails to individual instructors for individual concerns, such as your data analysis project or personal matters.


## Prerequisites

The course is suitable for students with a large range of prior exposure to statistics and mathematics.
No prior statistical, mathematical, or programming experience is necessary beyond arithmetic, algebra, and elementary calculus.


<!-- # Evaluation -->


<!-- ## Data analysis project paper -->

<!-- Every student in this class will execute their own statistical data analysis of a research question. -->
<!-- The results of this analysis will be presented as a paper due at the end of the course. See the [schedule](/schedule/#finals-period) for the due date. -->

<!-- The purpose of this paper is for the students to apply the quantitative methods used in this course to the real-world research problems that they will encounter in their research careers. -->
<!-- However, due to the limited time in this course, it is not necessary for this paper to address an important research problem or a novel contribution to the literature. -->
<!-- While those will not be criteria for the evaluation of this paper, the author is encouraged to pursue those, as they are what leads to publications. -->
<!-- The paper will be evaluated on the appropriateness of the statistical methods applied to the data and question, and not the novelty or contribution of the question itself. -->

<!-- If you developed a research design for POLS 500, you may be able to use it in 501. -->
<!-- However you need to confirm that you will be able to assemble a dataset to test a specific research hypothesis within the time constraints of this course, because you will be using it throughout the course. If that seems unlikely, you will need to choose a different project. -->


<!-- ## Assignments -->

<!-- There will be weekly assignments. Each assignment will consist of up to five different parts. No late homework will accepted except in the case of a documented emergency. Assignments will be submitted via Canvas. -->

<!-- 1. *Reading questions*: For each week students will be expected to complete questions on the reading for that week, which will be due at the start of class. We will grade on a CR/NC basis (including half grades between these categories). Credit will be granted if the student gives an honest effort in completing the assignment. Given that statistics is effectively learned by solving problems in one form or another, these questions should not be considered "in addition to reading", but should be considered the assigned readings. These assignments will be due at the start of Thurs class. -->
<!-- 2. *Corrected reading questions*: The key for reading questions will be given at each class, and some of class can be spent reviewing any problems students had with the questions. Corrected reading questions will be due at the start of class the following week. The correction should take the form of comments added to the original homework that -->
<!-- indicate where mistakes were made and that demonstrate an understanding of those mistakes. These will be graded on a CR/NC basis. -->
<!-- 3. *Research project assignments*: Each week students will complete an assignment that makes some progress on their research project. These will generally apply the concepts covered to their research projects. These assignments will be due at the start of Thurs class. -->
<!-- 4. *Peer review assignments*: There will be several assignments in which students are asked to peer review the research projects of other students in the course. These assignments will be due at the start of Thurs class. -->
<!-- 5. *Computing assignments*: These assignments will apply concepts to real or simulated data using R. These assignments will be due at the start of Fri lab. -->


## Materials


### Textbooks

<!-- - Gailmard, Sean. 2014. *Statistical Modeling and Inference for Social Science*. [amazon](http://www.amazon.com/Statistical-Modeling-Inference-Analytical-Research/dp/1107003148/). -->
<!-- - Diez, David M., Christopher D Barr, and Mine Çetinkaya-Rundel. *OpenIntro Statistics*. 3rd ed. <https://www.openintro.org/stat/textbook.php>. (This textbook is free) -->
<!-- - Lander, Jared P. 2013. *R for Everyone: Advanced Analytics and Graphics*. [amazon](http://www.amazon.com/Everyone-Advanced-Analytics-Graphics-Addison-Wesley/dp/0321888030). -->

### Software and Computing

This course will use [R](https://www.r-project.org/), which is a free and open-source programming language primarily used for statistics and data analysis. We will also use [RStudio](https://www.rstudio.com/), which is an easy-to-use interface to R. Instructions to install them are [here](/resources/install/).

<!-- Additionally, [Data Camp](https://www.datacamp.com/), a website which provides online interactive R tutorials, will be used to teach R. Although it is not free, there is a [student subscription rate](https://www.datacamp.com/enroll-student). -->

Students should have a laptop that they can bring to both class and lab as we will integrate computing with learning data analysis and statistics throughout the course.



## Resources

Beyond what the teaching team can providing, there are several resources on campus that you can go for assistance with data, computing, and statistical problems:

-  Center for Social Science Computing and Research ([CSSCR](http://julius.csscr.washington.edu/about/consulting.html)) has a drop-in statistical consulting center in Savery 119. They provide consulting on statistical software, e.g. R. Go there for software or data related questions.
- [CSSS Statistical Consulting](https://www.csss.washington.edu/consulting) provides general statistical consulting. Go there for questions about statistical methods.
- [eScience Data Science Office Hours](http://escience.washington.edu/office-hours/)


## License

Science should be open, and this course builds up other open licensed material, so unless otherwise noted, all materials for this class are licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

The source for the materials of this course is on GitHub at <a href="https://github.com/UW-POLS501/pols_501_wi17">UW-POLS501/pols_501_wi17</a>

## Bugs

If you find any typos or other issues in this page, any page in the site go to [issues](https://github.com/UW-POLS501/pols_501_wi17/issues), click on the "New Issue" button to create a new issue, and describe the problem.



<!-- This course has benefitted from numerous open materials, which are listed [here](https://github.com/UW-POLS501/pols_501_wi16/blob/master/notes/references.md). On this page, the learning objectives from this course are derived from Mine Çetinkaya-Rundel's [Duke Sta 101](https://stat.duke.edu/courses/Fall15/sta101.002/syllabus/) syllabus. -->
<!-- The idea for self-correction is from Matt Blackwell's [Harvard GOV 2000](http://www.mattblackwell.org/files/teaching/gov2000-syllabus.pdf). -->

