---
title: "Research Project"
---

See the [schedule](schedule.html) for due dates.


# Draft Proposal   {#draft-proposal}

In one to two paragraphs propose a research project for this course.
State your research question.
Describe what data you will be using to address that question.
If you were in POLS 500, will this be a continuation of your POLS 500 final project?

The primary purpose of this proposal is to get you thinking about your question immediately and put an idea on paper.
We will be able to give feedback, and you can adjust your proposal in the next draft.

Turn in as a `.pdf` file via [Canvas](https://canvas.uw.edu/courses/1098109/assignments/3566710).


# Research Proposal    {#proposal}

In one to two paragraphs propose a research project for this course.
State your research question.
Describe what data you will be using to address that question.

1. Address any comments from the first proposal.
2. What is your research question or puzzle?
3. Is the research question descriptive, causal, or predictive?
4. What is the outcome variable of interest? What are the explanatory variables?
5. What data will you be using? What is the location of the data (include links to the data).
   Will your data be coming from one of many sources?
   What format(s) are the data in?
   How do you intend to operationalize the concepts in your question with the data
   at hand?
6. What issues are you having or expect to have in getting and cleaning this data?

Try to answer these questions as best as possible.
If you don't know, state it; we'll discuss it.
If you are having problems describe them; that's why item 6 is there.
Research projects are an iterative and stochastic process; the purpose of these
assignments is to focus you on certain parts, find the problems and overcome them.


Turn in a `.pdf` file via [Canvas](https://canvas.uw.edu/courses/1098109/assignments/3578633)

# Data Analysis 1: Data Availability   {#data-analysis-1}

This is to check-in on your progress.

- What are your data sources? Cite the data appropriately using name or title of the data set, authors, version, creation date, and persistent data identifier (e.g. DOI) if available or URL if one is not. See [Political Analysis guidelines](https://academic.oup.com/pan/pages/Instructions_To_Authors) for data citation.
- What is the current status of your data acquisition and wrangling? What challenges have you encountered, and what challenges are you still having?

Turn in a `.pdf` file via [Canvas]().


# Data Analysis 2: EDA    {#data-analysis-2}

- State your research question.
- Describe and document your research sources. Cite all data used using a proper data citation.

Some questions that should be answered:

- What are the number of observations? What is the unit of analysis, what is the unit of observation?
- How do the variables in your data set relate to the variables in your theory? In other words, how are you operationalizing your concepts? Justify that operationalization, and acknowledge any shortcomings of it.
- What was the sampling process for your sample of observations?
- What is the number of observations for your data?
- Are there any missing values in the variables of interest?
- Are there any outliers in the variables of interest?
- Provide a summary statistic table in the format common to social science journals: non-missing observations, mean, standard deviation, min max. Find a recent journal article for how these are formatted.
- For *at least* the outcome variable(s) and the covariates of interest, visualize their distributions using the appropriate data visualization methods.
- For all outcome variables and the covariates of interest visualize the relationship between the outcome and covariates of interest using the appropriate data visualization methods.
- Apply k-means clustering to your data in a meaningful way. If you have multiple measures of something similar this may be a way to reduce the dimensions.

For this assignment both a document and reproducible code will be turned in.

Submit by either sharing a Dropbox or Google Drive folder, or submitting a `.zip` file to [Canvas](https://canvas.uw.edu/courses/1098109/assignments/3590026).
In your submission you must include the document and any code and data needed to generate the results in that  document.


# Data Analysis 3: Regression and Prediction {#data-analysis-3}

Address any comments from [Data Analys 2](#data-analysis2).

For all explanatory variables of interest, characterize the unconditional
relationship between it and the outcome variable(s) of interest.
Use visual methods and linear regression.

If your analysis has a causal question:

- What is your identification strategy: randomization, regression discontinuity,
  before-and-after, diff-in-diff, or selection on observables?  In general,
  consider how you are generating the counterfactual. Implement that method.
- If your identification strategy is selection on observables: What variables
  are possible confounders? Do you have observable measures for them? Think of
  at least one possible confounder that you don't have a measure for.
- Account for these confounding variables in two ways:

  - dividing your regression
  - controlling for them in the regression

If your analysis is a predictive question:

- Compare the model fits of the following models using adjusted R squared or cross-validation.

  - reference model(s): no variables, all variables other than the variable of interest
  - a model using only the explanatory variable of interest
  - a model using all variables


The following were suggestions for answering the research question.
If there is other quantitative analysis that you think better answers your research question, do it!
All methods are in service of answering the question, not vice versa.

For this assingment, you should not be worrying about uncertainty.
Focus on using methods that match the question you are answering.
In the next assignment(s) you will be asked to consider uncertainty in your
analysis due to sampling.

Submission instructions: submit a **zip** file of the directory containing **all** your code and data to reproduce your analysis. Follow the submission
templates.

**Note**: You must submit a zip file even if you shared a Dropbox folder.
This is to provide a snapshot of the project at the time of submission that the instructors can comment on.
The reason for requiring a snapshot is a worry about further work after submission, not due to it affecting the grade, but because further work by the student may break previous working code and it would be too much work for you to ensure that the code from this project continued to work as you continue to work on the project.

**Submissions must have code that runs. If the analysis is not reproducible it will not be accepted.**


# Data Analysis 4: Hypothesis Testing   {#data-analysis-4}

Address theoretical, data, and methodological issues from the previous data analysis assignments.

In addition, consider the uncertainty of your results using confidence intervals, p-values, and cross-validation.

Write up your analysis in a readable document. This can either be a R markdown file or a Word, LaTeX, or PDF file with a separate R script to produce the results. Whatever your preferred method, it must be clear to the reader where to look for your analysis, and the analysis must be written for an outsider reader to understand.


**Note**: Upload a zip file of your entire project directory as a zip file to canvas.  This should include all code and data necessary to reproduce your results, and should follow the project template guidelines.

Upload a zip file even if you have shared your Dropbox folder with us. This is to provide a snapshot of the project at the time of submission that the instructors can comment on without disrupting your continued work on your project.

# Final Paper    {#final}

The final paper should be a well-crafted quantitative analysis of a research question of less than 10,000 words.
It should employ the relevant, but not necessarily all, of the methodologies covered in this course---data visualization, descriptive statistics, exploratory data analysis, statistical tests, linear regression---to answer the research question that was posed.
While the student is encouraged to find interesting and original research questions that could eventually lead to publication in an academic journal, the final paper will be evaluated on how well it is crafted and the appropriate use of methodologies to answer the research question as it was posed.

All analysis presented must be reproducible and the manuscript must be formatted according the guidelines.

## Reproducibility policy

All data and code necessary to reproduce the analyses presented in the paper must be provided.
The data and analyses should be well documented and understandable to a reader.
In particular, it should be clear how the code relates to the analyses presented in the paper.
The analysis code must run and reproduce the analyses as presented in the paper.
Authors are encouraged to use literate programming tools such as R Markdown and knitr.

It must be well-organized, and should adhere to the principles, if not the recommendations of [Good Enough Practices for Scientific Computing](https://arxiv.org/pdf/1609.00037v2.pdf).
Students are strongly encouraged to start with the provided [project template](https://github.com/UW-POLS501/project_template).
At a minimum, it *must* contain a `README.md` file which describes the organization of the projects and instructions on how to reproduce the analysis.

The project should be in a Dropbox <!-- or Google Drive --> folder shared with the instructor.

If there are issues of confidentiality or privacy that prevent the author from directly sharing their data with the instructor, they should consult with the instructor as soon as possible.


## Formatting Guidelines

Templates which follow the formatting guidelines are available for:

- [Word](https://github.com/jrnold/psmanuscripts/raw/master/templates/manuscript.docx)
- [LaTeX](https://github.com/jrnold/psmanuscripts/raw/master/templates/manuscript.tex)
- [R Markdown](https://github.com/jrnold/psmanuscripts)

### Main Text

Your final paper should be less than 10,000 words.
This word counts includes all text (the abstract is text), tables and figures, notes, references and appendices included in the manuscript.
Font size must be a standard 12 point serif font.
The manuscript must be double spaced for all body text including the references, but text in tables and figures may be single spaced.
Page margins must be one inch.

The submission must include a title page with the title of the paper, the author's name, date, an abstract of no more than 150 words, and the word count.
The abstract should concisely state the literature to which the paper contributes, the specific topic it addresses, the methodology employed for the analysis, the results of the analysis, and the implications of the findings.

The manuscript should present its content as efficiently as possible.
It should **not** contain a literature review.
State the research puzzle, your theory, and how it compares to previous approaches.
Cite the directly relevant works where necessary to support your argument.
It should not contain a table of contents like paragraph at the end of the introduction.

### Numbers, Tables, and Figures

Tables and figures should be included where they fall in the text, and not in an appendix. Tables and figures should be formatted for publication.
In particular do not include the direct output of software such as R.
They should be clear, readable, and easily understandable.
In formatting tables and figures should generally follow the guidelines for "Tables and Figures" in [Political Analysis](https://academic.oup.com/pan/pages/Instructions_To_Authors).

You are encouraged to use graphics to illustrate your main argument and research findings.
If color is used, then it should be used appropriately, following the  best practices in data visualization.

Numbers used in the manuscript text, figures, and tables should be reported with no more precision than they are measured with or is substantively meaningful.
A good rule of thumb is to use no more than 2 digits unless there is good reason to do so.
Do not report more significant digits than the standard errors imply.
Variables should be scaled to make the reporting of results as straightforward as possible.
If variables are on vastly different scales, then they should be rescaled to produce estimates on similar scales.
Uncertain numbers should be accompanied by an indication of their uncertainty, generally a standard error or confidence interval.

The uncertainty of estimates is best conveyed by standard errors or confidence intervals.
Generally, tables should not routinely report t-statistics or p-values for tests of the null hypothesis that each coefficient is zero.
Do not use asterisks, "stars", or other symbols to represent varying levels of statistical significance.
Regression tables should report the estimate and standard errors of the coefficients, without stars indicating significance levels.
In an author states that a test is "statistically significant", it must be at the .05 level or lower.

### Supporting information

The use of supporting information beyond that of the manuscript is encouraged.
This can include additional analyses that are referenced in the text, but not fully presented.
In particular, the main text should include the main specifications with robustness checks and alternative specifications briefly summarized, but provided in the supporting materials.

### Footnotes

Explanatory footnotes may be included but should not be used for simple citations.
Simple citations should be made in-line in author-year format.
Do not use end notes.
Do not use acronyms or computational abbreviations when discussing variables in the text.
All variables that appear in tables or figures should be described in appropriate detail in the text.

### Citations and References

References should be listed in a separate section titled "References."
Citations should be in the author-year format, and references should follow the formats common to political science journals. This is generally the *Chicago Manual of Style* author-year format.
It is best to start getting used to using a [reference manager](https://en.wikipedia.org/wiki/Reference_management_software) such as [Zotero](https://www.zotero.org/), [Mendeley](https://www.mendeley.com/), [Papers](http://papersapp.com/), [Colwiz](https://www.colwiz.com/), [Endnote](http://endnote.com/), or BibTeX (with [JabRef](http://www.jabref.org/)]).
These both store references and format citations and references according to specified styles.

### Data citation

All data used in the paper must be cited.
Citations must include enough information for readers to find the original sources, and for those original sources to be consistently identified in the future.
Data citations should appear in the the manuscript's reference list, contain the name or title of the data set, the author(s), version, date of creation, and a persistent data identifier, such as a DOI, if one is available.
If a persistent identifier is not available, include a URI if one is available.



### Sources for these guidelines

These guidelines are derived from the current manuscript guidelines for top political science journals: [APSR Submission Guidelines](http://www.apsanet.org/APSR-Submission-Guidelines-August-2016), [AJPS Guidelines for Manuscripts](https://ajps.org/guidelines-for-manuscripts/), [AJPS Guidelines for Preparing Replication Files](https://ajpsblogging.files.wordpress.com/2015/03/ajps-guide-for-replic-materials-1-0.pdf), [Journal of Politics Instructions for Authors](http://www.journals.uchicago.edu/journals/jop/instruct), [Political Analysis Information a Authors and Reviewers](https://academic.oup.com/pan/pages/Instructions_To_Authors).
