---
title: Schedule
---

```{r include=FALSE, results='hide'}
library("lubridate")
library("stringr")
dtfmt <- function(x) format(ymd(x), "%a, %b %d")
```


> "No plan survives contact with the enemy"
> --- paraphrased quote of [Helmuch von Moltke the Elder](https://en.wikiquote.org/wiki/Helmuth_von_Moltke_the_Elder)


This schedule is an approximation, subject to change due needs of the students in the course.
Students will be informed of changes to the schedule.


# Research Project 

The final version of the paper for the research project is due **Thurs, March 16, 17:00 PDT**.

Prior to the final paper being due there will be approximately weekly assignments in order to provide feedback, and allow you to immediately implement concepts and methods learned in the course. 

See [research project](research_project.html) page for instructions.

-------------------  ---------------------------
**Draft Proposal**   `r dtfmt("2017-01-10")`
**Proposal**         `r dtfmt("2017-01-17")`
**Data Analysis 1**  `r dtfmt("2017-01-24")`
**Data Analysis 2**  `r dtfmt("2017-02-07")`
**Data Analysis 3**  `r dtfmt("2017-02-21")`
**Data Analysis 4**  `r dtfmt("2017-02-28")`
**Paper Draft**      `r dtfmt("2017-03-07")`
-------------------  ---------------------------



# Readings, Assignments, Lectures

Abbreviations:

------------- ----------------------------------------------------------------------------------------------------------------------------------------
*R4DS*        Wickham and Grolemund, [R for Data Science](http://r4ds.had.co.nz/)
*QSS*          Imai, *A First Course in Quantitative Social Science*
*OpenIntro*    [OpenIntro Statistics, 3rd edition](https://www.openintro.org/stat/textbook.php?stat_book=os)
*RealStats*    Bailey, *Real Stats*
------------- ----------------------------------------------------------------------------------------------------------------------------------------

## Week 1

### Class (January 3rd)

- *r4ds* Ch 1: Introduction
- *r4ds* Ch 2: Explore -- Introduction
- *QSS* Ch 1

### Lab (January 7th)

- [Data Camp Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r)
- *r4ds* Ch 3: Data visualization
- *r4ds* Ch 4: Workflow basics
- Wickham, Hadley. 2010. "[A Layered Grammar of Graphics](http://vita.had.co.nz/papers/layered-grammar.html)." *Journal of Computational and Graphical Statistics*.
- *r4ds* Ch 6: Workflow scripts

Optional

- [Data Camp ggplot 1](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)
- [Data Camp ggplot 2](https://www.datacamp.com/courses/data-visualization-with-ggplot2-2)
- [Data Camp ggplot 3](https://www.datacamp.com/courses/data-visualization-with-ggplot2-part-3)


## Week 2

### Class (January 10)

- *r4ds* Ch 5: Data transformation
- *r4ds* Ch 9: Wrangle: Introduction
- *r4ds* Ch 10: Tibbles
- *r4ds* Ch 11: Data import

Optional

- [Introduction to dplyr](https://cran.r-project.org/web/packages/dplyr/vignettes/introduction.html)
- [Window functions and grouped mutate/filter](https://cran.r-project.org/web/packages/dplyr/vignettes/window-functions.html)
- [Data Manipulation in R with dplyr](https://www.datacamp.com/courses/cleaning-data-in-r) 
- [Data Camp: Importing Data in R I](https://www.datacamp.com/courses/importing-data-in-r-part-1) This covers importing flat files but uses base R, instead of the **readr** package
- [Data Camp: Importing Data in R](https://www.datacamp.com/courses/importing-data-in-r-part-2) This covers importing data.
- [tibble 1.0.0](https://blog.rstudio.org/2016/03/24/tibble-1-0-0/)
- [readr 1.0.0](https://blog.rstudio.org/2016/08/05/readr-1-0-0/)
- Swirl *Getting and Cleaning Data* (Manipulating data with dplyr; Grouping and chaining with dplyr)

### Lab (January 13)

- *r4ds* Ch 8: Workflow projects
- *r4ds* Ch 7: EDA

## Week 3

### Class (January 17th)

Assignment 1 due: use the [R template](https://github.com/UW-POLS501/pols_501_wi17/raw/master/files/assignment1.R) and [Word document template](https://github.com/UW-POLS501/pols_501_wi17/raw/master/files/assignment1-template.docx) for your solutions.

- *QSS* Ch 2: Causality
- *QSS* Ch 3: Measurement
- *r4ds* Ch 12: Tidy Data
- Wickham, Hadley. 2014. "[Tidy Data](http://vita.had.co.nz/papers/layered-grammar.html)" *Journal of Statistical Software*.

Optional

- [Cleaning data in R](https://www.datacamp.com/courses/cleaning-data-in-r)
- Swirl *Getting and Cleaning Data* (Tidying data with tidyr)

### Lab (January 20th)

- *r4ds* Ch 13: Relational data
- *r4ds* Ch 14: Strings
- *r4ds* Ch 15: Factors
- *r4ds* Ch 16: Dates and times
- *r4ds* Ch 20: R Markdown workflow


Optional

- [Two-table verbs](https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html)
- Data Camp [Reporting with R markdown](https://www.datacamp.com/courses/reporting-with-r-markdown)
- Data Camp [Joining Data in R with dplyr](https://www.datacamp.com/courses/joining-data-in-r-with-dplyr)
- [Introduction to stringr](https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html)
- [Do more with dates and time in R with lubridate 1.3.0](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html)
- [Regular-Expressions.info](http://www.regular-expressions.info/tutorial.html)
- Swirl *Getting and Cleaning Data* (Dates and Times with lubridate)

## Week 4

### Class (January 24th)

- *QSS* Ch 4: Prediction
- *OpenIntro* Ch 7: Introduction to linear regression
- *RS* Ch 3.1 "Bivariate Regression Model"
- *r4ds* Ch 17: Program: Introduction
- *r4ds* Ch 18: Pipes
- *r4ds* Ch 19: Functions

Optional 

- [Data Camp: Intermediate R](https://www.datacamp.com/courses/intermediate-r)
- [Data Camp: Writing Functions in R](https://www.datacamp.com/courses/writing-functions-in-r)



### Lab (January 27th)

- *r4ds* Ch 27: R Markdown
- *r4ds* Ch 29: R Markdown formats
- *r4ds* Ch 20: Vectors
- *r4ds* Ch 21: Iteration

## Week 5

class
:   Jan 31

lab
:   Feb 3

- *QSS* Ch 5: Discovery


## Week 6

### Class (February 7th)

- *QSS* Ch 6: Probability
- *OpenIntro* Ch 2: Probability
- *OpenIntro* Ch 3: Distributions of Random Variables

### Lab (February 10th)


## Week 7

### Class (Feb 14th)


- *r4ds* Ch 25: Many Models

### Lab (Feb 17th)

## Week 8

### Class (Feb 21st)

- *QSS* Ch 7: Uncertainty
- *OpenIntro* Ch 4: Foundations for inference
- *OpenIntro* Ch 5: Inference for numerical data
- *OpenIntro* Ch 6: Inference for categorical data

### Lab (Feb 24th)

## Week 9

### Class (February 28th)


### Lab (March 3rd)


## Week 10

### Class (March 7th)


### Lab (March 10th)

- *r4ds* Ch 26: Communicate: Introduction
- *r4ds* Ch 28: Graphics for communication

